changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security and dependencies
      labels:
        - security
        - dependencies
    - title: New capabilities
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - bugfix
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
